"""Chapter 02: 数据中的共同变化.

Textbook data: 国家统计局 70 个大中城市商品住宅销售价格指数（2025）。

教学对应关系：
    教材变量 living_area -> 新建商品住宅同比价格指数
    教材变量 price       -> 二手住宅同比价格指数

This script mirrors the chapter's original code order: covariance, Pearson
correlation, Spearman rank correlation, simple linear regression, and R^2.
It intentionally uses only pandas/numpy so it can run in a minimal environment.
Figures with Chinese labels are generated by the companion R script.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


SCRIPT_DIR = Path(__file__).resolve().parent
CHAPTER_DIR = SCRIPT_DIR.parent
REPO_DIR = CHAPTER_DIR.parent
DATA_PATH = REPO_DIR / "data" / "processed" / "nbs_70city_house_price_2025.csv"
TABLE_DIR = CHAPTER_DIR / "tables"
RESULT_DIR = CHAPTER_DIR / "results"

TABLE_DIR.mkdir(parents=True, exist_ok=True)
RESULT_DIR.mkdir(parents=True, exist_ok=True)


raw = pd.read_csv(DATA_PATH, encoding="utf-8-sig")

new_house = raw.loc[
    raw["market"].eq("new_house"),
    ["city", "date", "year", "month", "mom_index", "yoy_index"],
].rename(
    columns={
        "mom_index": "new_house_mom",
        "yoy_index": "new_house_yoy",
    }
)

second_hand = raw.loc[
    raw["market"].eq("second_hand"),
    ["city", "date", "year", "month", "mom_index", "yoy_index"],
].rename(
    columns={
        "mom_index": "second_hand_mom",
        "yoy_index": "second_hand_yoy",
    }
)

df = (
    pd.merge(new_house, second_hand, on=["city", "date", "year", "month"])
    .sort_values(["date", "city"])
    .reset_index(drop=True)
)
df = df.dropna(subset=["new_house_yoy", "second_hand_yoy"]).copy()

df.to_csv(RESULT_DIR / "python_chapter02_70city_wide_analysis_data.csv", index=False)

# ------------------------------------------------------------------------------
# Box 01--02: Python 中相关的计算
# ------------------------------------------------------------------------------

x = df["new_house_yoy"]
y = df["second_hand_yoy"]

# ------------------------------------------------------------------------------
# Box 03: 样本均值和样本量
# ------------------------------------------------------------------------------

xbar = x.mean()
ybar = y.mean()
n = len(df)

missing_check = pd.DataFrame(
    {
        "variable": ["new_house_yoy", "second_hand_yoy"],
        "missing_count": [df["new_house_yoy"].isna().sum(), df["second_hand_yoy"].isna().sum()],
    }
)
missing_check.to_csv(RESULT_DIR / "python_chapter02_missing_value_check.csv", index=False)

# ------------------------------------------------------------------------------
# Box 04: 样本协方差
# ------------------------------------------------------------------------------

s_xy = ((x - xbar) * (y - ybar)).sum() / (n - 1)

# ------------------------------------------------------------------------------
# Box 05: 两个变量的样本方差
# ------------------------------------------------------------------------------

s_x2 = ((x - xbar) ** 2).sum() / (n - 1)
s_y2 = ((y - ybar) ** 2).sum() / (n - 1)

# ------------------------------------------------------------------------------
# Box 06--08: Pearson 相关系数
# ------------------------------------------------------------------------------

corr_xy_manual = s_xy / (np.sqrt(s_x2) * np.sqrt(s_y2))
corr_xy_pandas = x.corr(y, method="pearson")
corr_xy_cov = x.cov(y) / (x.std(ddof=1) * y.std(ddof=1))

covariance_table = df.loc[
    :9, ["city", "date", "new_house_yoy", "second_hand_yoy"]
].copy()
covariance_table["x_minus_xbar"] = covariance_table["new_house_yoy"] - xbar
covariance_table["y_minus_ybar"] = covariance_table["second_hand_yoy"] - ybar
covariance_table["product_xy"] = (
    covariance_table["x_minus_xbar"] * covariance_table["y_minus_ybar"]
)
covariance_table_cn = covariance_table.rename(
    columns={
        "city": "城市",
        "date": "月份",
        "new_house_yoy": "新房同比指数",
        "second_hand_yoy": "二手房同比指数",
        "x_minus_xbar": "新房偏离均值",
        "y_minus_ybar": "二手房偏离均值",
        "product_xy": "偏离乘积",
    }
)
covariance_table_cn.to_csv(TABLE_DIR / "python_chapter02_covariance_table.csv", index=False)

# ------------------------------------------------------------------------------
# Box 09--13: Spearman 秩相关系数
# ------------------------------------------------------------------------------

df["Rx"] = df["new_house_yoy"].rank(method="average")
df["Ry"] = df["second_hand_yoy"].rank(method="average")

mean_Rx = (n + 1) / 2
mean_Ry = (n + 1) / 2

covRxRy = ((df["Rx"] - mean_Rx) * (df["Ry"] - mean_Ry)).sum() / (n - 1)
sRx = np.sqrt(((df["Rx"] - mean_Rx) ** 2).sum() / (n - 1))
sRy = np.sqrt(((df["Ry"] - mean_Ry) ** 2).sum() / (n - 1))

rS = covRxRy / (sRx * sRy)
rS_alt = df["Rx"].corr(df["Ry"], method="pearson")

rank_table = df.loc[
    :9, ["city", "date", "new_house_yoy", "second_hand_yoy", "Rx", "Ry"]
].rename(
    columns={
        "city": "城市",
        "date": "月份",
        "new_house_yoy": "新房同比指数",
        "second_hand_yoy": "二手房同比指数",
        "Rx": "新房秩",
        "Ry": "二手房秩",
    }
)
rank_table.to_csv(TABLE_DIR / "python_chapter02_rank_table.csv", index=False)

# ------------------------------------------------------------------------------
# Box 15--21: 简单线性回归与判定系数
# ------------------------------------------------------------------------------

beta_1_hat = s_xy / s_x2
beta_0_hat = ybar - xbar * beta_1_hat

y_hat = beta_0_hat + beta_1_hat * x
u_hat = y - y_hat

RSS = float((u_hat**2).sum())
TSS = float(((y - ybar) ** 2).sum())
R2 = 1 - RSS / TSS

sum_xx = float(((x - xbar) ** 2).sum())
sigma2_hat = RSS / (n - 2)
se_beta_1 = np.sqrt(sigma2_hat / sum_xx)
se_beta_0 = np.sqrt(sigma2_hat * (1 / n + xbar**2 / sum_xx))

summary_table = pd.DataFrame(
    {
        "指标": [
            "样本量",
            "新房同比指数均值",
            "二手房同比指数均值",
            "样本协方差",
            "新房同比指数方差",
            "二手房同比指数方差",
            "Pearson相关系数_手算",
            "Pearson相关系数_pandas",
            "Pearson相关系数_cov",
            "Spearman秩相关系数_手算",
            "Spearman秩相关系数_rank_corr",
            "OLS截距",
            "OLS斜率",
            "OLS截距标准误",
            "OLS斜率标准误",
            "RSS",
            "TSS",
            "R2",
        ],
        "数值": [
            n,
            xbar,
            ybar,
            s_xy,
            s_x2,
            s_y2,
            corr_xy_manual,
            corr_xy_pandas,
            corr_xy_cov,
            rS,
            rS_alt,
            beta_0_hat,
            beta_1_hat,
            se_beta_0,
            se_beta_1,
            RSS,
            TSS,
            R2,
        ],
    }
)
summary_table.to_csv(RESULT_DIR / "python_chapter02_summary.csv", index=False)

lm_lines = [
    "第 2 章：数据中的共同变化",
    "",
    "数据：国家统计局 70 个大中城市商品住宅销售价格指数（2025 年月度）。",
    "X：新建商品住宅同比价格指数；Y：二手住宅同比价格指数。",
    "",
    f"完整样本量：{n}",
    f"Pearson 相关系数：{corr_xy_pandas:.4f}",
    f"Spearman 秩相关系数：{rS_alt:.4f}",
    f"OLS：二手房同比指数 = {beta_0_hat:.4f} + {beta_1_hat:.4f} * 新房同比指数",
    f"截距标准误：{se_beta_0:.4f}",
    f"斜率标准误：{se_beta_1:.4f}",
    f"R^2：{R2:.4f}",
]
(RESULT_DIR / "python_chapter02_lm_summary.txt").write_text("\n".join(lm_lines), encoding="utf-8")

print("\n".join(lm_lines))
